# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_expa', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('code_expa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cumplido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('code_comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcperformance.comite')),
            ],
        ),
        migrations.CreateModel(
            name='custumer_stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code_expa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='focus_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('period', models.IntegerField()),
                ('code_comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcperformance.comite')),
            ],
        ),
        migrations.CreateModel(
            name='od_stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type_expa', models.CharField(max_length=50)),
                ('code_expa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='target_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField()),
                ('code_comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcperformance.comite')),
                ('code_custumer_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcperformance.custumer_stage')),
                ('code_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcperformance.product')),
            ],
        ),
        migrations.CreateModel(
            name='weekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateField()),
                ('final_date', models.DateField()),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='target_product',
            name='code_weekly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcperformance.weekly'),
        ),
        migrations.AddField(
            model_name='focus_product',
            name='code_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcperformance.product'),
        ),
        migrations.AddField(
            model_name='cumplido',
            name='code_custumer_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcperformance.custumer_stage'),
        ),
        migrations.AddField(
            model_name='cumplido',
            name='code_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcperformance.product'),
        ),
        migrations.AddField(
            model_name='comite',
            name='code_od_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcperformance.od_stage'),
        ),
    ]
