# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcperformance', '0002_remove_comite_codigo_expa'),
    ]

    operations = [
        migrations.CreateModel(
            name='aplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_secret', models.CharField(max_length=250)),
                ('podio_id', models.IntegerField()),
                ('unique_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_podio', models.CharField(max_length=250)),
                ('password_podio', models.CharField(max_length=250)),
                ('id_cliente_podio', models.CharField(max_length=250)),
                ('codigo_secreto_podio', models.CharField(max_length=250)),
                ('user_expa', models.CharField(max_length=250)),
                ('password_expa', models.CharField(max_length=250)),
            ],
        ),
    ]
