# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcperformance', '0003_aplicacion_user_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comite',
            name='code_expa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
