# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcperformance', '0004_auto_20170927_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='comite',
            name='code_podio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
